server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/marquez
  user: marquez
  password: marquez

logging:
  level: DEBUG
  appenders:
    - type: console
      threshold: DEBUG
  loggers:
    marquez.db: DEBUG
    marquez.service: DEBUG
    marquez: DEBUG
    org.eclipse.jetty: INFO
    org.jdbi: DEBUG
    org.postgresql: DEBUG     